# DATA DIRS
CHEMBL_LOCAL_DIR: "/home/jack/unm_gra/data/chembl/"
DATA_DIR: "/home/jack/unm_gra/data/LAA/"

# ChEMBL FILES
# NOTE: to update ChEMBL version just change "35" to desired version
CHEMBL_POSTGRES_DB_LINK: "https://ftp.ebi.ac.uk/pub/databases/chembl/ChEMBLdb/latest/chembl_35_postgresql.tar.gz"

# DB OPTIONS
CHEMBL_DB_NAME: "chembl_35"
CHEMBL_DB_HOST: "localhost"
CHEMBL_DB_USER: "toad"
CHEMBL_DB_PASSWORD: "cookies"
CHEMBL_DB_PORT: 5432

# PROTEIN TARGET SELECTION
ORGANISM: "Homo sapiens"
TARGET_TYPE: "SINGLE PROTEIN"
PROTEIN_CLASS_ID: 1100 # 1100 corresponds to protein kinase family - see protein_classification table

# ASSAY SELECTION
ASSAY_TYPE: "B" # B=binding, see https://chembl.gitbook.io/chembl-interface-documentation/frequently-asked-questions/chembl-data-questions#what-is-the-assay-type
CONFIDENCE_SCORE: 9
DOC_TYPE: "PUBLICATION" # only take assays associated w/ a publication
EXCLUDE_VARIANTS: TRUE # exclude assays looking at variant rather than wild-type of target

# LIGAND SELECTION
PCHEMBL_MIN_VALUE: 7.52 # potency threshold, defined as -log_10(measured val) M: >= 7.52 is same as <= 30nM
MIN_MW: 200 # minimum molecular weight in Da
MAX_MW: 900 # maximum ''
STRUCTURAL_ALERT_SET_IDS: "4" # can provide list like "1,2,3,4".  4=PAINS, see structural_alert_sets table

# LIGAND CLUSTERING (by target classification)
MIN_CLASS_LEVEL: 4 # note that 1100 has a class_level of 3
MAX_CLASS_LEVEL: 5

# LIGAND SIMILARITY CALCULATION
# make sure to set a reasonable limit here - current version of workflow takes O(N^2) time and space to create/store
# similarity matrix
MAX_N_COMPOUNDS: 20000

# PROBABILITY ANALYSIS
# looking at P(same cluster | sim > sim_threshold) = P(same cluster AND sim > sim_threshold) / P(sim > sim_threshold)
# this is of interest to see if it is more likely that two ligands will belong to the same 'cluster' (which could refer to protein group/family, individual protein targets, or assays) are more likely to be within that cluster than two randomly selected ligands
# NOTE: the 'population' of ligands here is currently the set of ligands identified as 'active' within the given PROTEIN_CLASS_ID
# I think the analyses could be improved (particularly for assays) if one considered all tested ligands within the group, but I haven't implemented this (it would also likely come with larger compute cost)
# Will calculate P(same cluster | sim > sim_threshold) for multiple sim_threshold values. These threshold values calculated as np.linspace(SIMILARITY_THRESHOLD_MIN, SIMILARITY_THRESHOLD_MAX, SIMILARITY_THRESHOLD_N)
SIMILARITY_THRESHOLD_MIN: 0.2
SIMILARITY_THRESHOLD_MAX: 0.9
SIMILARITY_THRESHOLD_N: 8

# DISTRIBUTION STAT ANALYSIS
# analyzing statistics/creating visualizations is expensive and
# may not make sense for all class levels (say class_levels with more than 15 families)
STAT_CLASS_LEVEL: 4
