# DATA DIRS
CHEMBL_LOCAL_DIR: "/home/jack/unm_gra/data/chembl/"
DATA_DIR: "/home/jack/unm_gra/data/LAA/"

# ChEMBL FILES
# NOTE: to update ChEMBL version just change "35" to desired version
CHEMBL_POSTGRES_DB_LINK: "https://ftp.ebi.ac.uk/pub/databases/chembl/ChEMBLdb/latest/chembl_35_postgresql.tar.gz"

# DB OPTIONS
CHEMBL_DB_NAME: "chembl_35"
CHEMBL_DB_HOST: "localhost"
CHEMBL_DB_USER: "toad"
CHEMBL_DB_PASSWORD: "cookies"
CHEMBL_DB_PORT: 5432

# PROTEIN TARGET SELECTION
ORGANISM: "Homo sapiens"
TARGET_TYPE: "SINGLE PROTEIN"
PROTEIN_CLASS_ID: 6 # 6 corresponds to kinase family - see protein_classification table
