# DATA DIRS
CHEMBL_LOCAL_DIR: "/media/jack/odisk/data/chembl/"
DATA_DIR: "/media/jack/odisk/data/LAA/"

# ChEMBL FILES
# NOTE: to update ChEMBL version just change "35" to desired version
CHEMBL_POSTGRES_DB_LINK: "https://ftp.ebi.ac.uk/pub/databases/chembl/ChEMBLdb/latest/chembl_35_postgresql.tar.gz"

# DB OPTIONS
CHEMBL_DB_NAME: "chembl_35"
CHEMBL_DB_HOST: "localhost"
CHEMBL_DB_USER: "toad"
CHEMBL_DB_PASSWORD: "cookies"
CHEMBL_DB_PORT: 5434

# PROTEIN TARGET SELECTION
ORGANISM: "Homo sapiens"
TARGET_TYPE: "SINGLE PROTEIN"
PROTEIN_CLASS_ID: 6 # 6 corresponds to kinase family - see protein_classification table

# ASSAY SELECTION
ASSAY_TYPE: "B" # B=binding, see https://chembl.gitbook.io/chembl-interface-documentation/frequently-asked-questions/chembl-data-questions#what-is-the-assay-type
CONFIDENCE_SCORE: 9
DOC_TYPE: "PUBLICATION" # only take assays associated w/ a publication

# LIGAND SELECTION
PCHEMBL_MIN_VALUE: 7.52 # potency threshold, defined as -log_10(measured val) M: >= 7.52 is same as <= 30nM

