"""
@author Jack Ringer
Date: 7/14/2025
Description:
Helper functions related to reading the lower triangular (LTM)
matrix of similarity values generated by RDKit.
"""

import numpy as np


def get_ltm_idx(row: int, col: int) -> int:
    """
    In the LTM (e.g., from GetTanimotoSimMat), find the
    coefficient value between the given row/column.

    :param int row: index of molecule 1 in id_list ("row" in matrix)
    :param int col: index of molecule 2 in id_list ("column" in matrix)
    :return int: index in the LTM with coeff value
    """
    assert col < row
    offset = (row * (row - 1)) // 2
    return offset + col


def check_size(sim_matrix: np.ndarray, N: int):
    assert (
        len(sim_matrix.shape) == 1
    ), f"Expected LTM to be a 1D numpy array, given shape: {sim_matrix.shape}"
    assert len(sim_matrix) == (
        N * (N - 1) // 2
    ), "Mismatch between length of given id_list and LTM, check input"


def get_id2idx_map(id_list: list[int]) -> dict:
    return {cpd_id: i for i, cpd_id in enumerate(id_list)}
